<script src="{{ asset('template') }}/static/js/initTheme.js"></script>
<script src="{{ asset('template') }}/static/js/components/dark.js"></script>
<script src="{{ asset('template') }}/extensions/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="{{ asset('template') }}/compiled/js/app.js"></script>
<!-- Need: Apexcharts -->
<script src="{{ asset('template') }}/extensions/apexcharts/apexcharts.min.js"></script>
<script src="{{ asset('template') }}/static/js/pages/dashboard.js"></script>
<script src="{{ asset('template') }}/extensions/simple-datatables/umd/simple-datatables.js"></script>
<script src="{{ asset('template') }}/static/js/pages/simple-datatables.js"></script>
<script src="{{ asset('template') }}/extensions/jquery/jquery.min.js"></script>
